//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsGsmar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class evry1falls : global::System.Configuration.ApplicationSettingsBase {
        
        private static evry1falls defaultInstance = ((evry1falls)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new evry1falls())));
        
        public static evry1falls Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastGoodProxy {
            get {
                return ((string)(this["LastGoodProxy"]));
            }
            set {
                this["LastGoodProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastGoodUserAgent {
            get {
                return ((string)(this["LastGoodUserAgent"]));
            }
            set {
                this["LastGoodUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apps/GSMArenaUploaderApp")]
        public string AppFolderName {
            get {
                return ((string)(this["AppFolderName"]));
            }
        }
    }
}
