//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clsGsmar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FallbackData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FallbackData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clsGsmar.FallbackData", typeof(FallbackData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROXY:http://123.141.181.1:5031
        ///PROXY:http://103.173.230.217:8090
        ///PROXY:http://185.200.38.53:8080
        ///PROXY:http://45.146.163.31:80
        ///PROXY:http://159.203.61.169:3128
        ///PROXY:http://103.121.12.9:8080
        ///PROXY:http://151.236.24.38:80
        ///PROXY:http://47.89.159.212:80
        ///PROXY:http://164.68.101.70:8888
        ///PROXY:http://134.209.29.120:80
        ///PROXY:http://139.59.1.14:8080
        ///PROXY:http://8.213.197.208:6379
        ///PROXY:http://51.79.207.21:8080
        ///PROXY:http://8.211.194.78:8443
        ///PROXY:http://167.86.93.118:8049
        ///PROXY:http://8.220.205.172 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProxyAndUserAgentFallback {
            get {
                return ResourceManager.GetString("ProxyAndUserAgentFallback", resourceCulture);
            }
        }
    }
}
